# Generated by Django 2.1 on 2018-09-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0003_auto_20180904_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default='2018-08-27T10:27:17.740810+03:00'),
        ),
    ]
