# Generated by Django 2.1 on 2018-09-07 11:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0005_auto_20180904_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icon',
            name='marker',
        ),
        migrations.AddField(
            model_name='marker',
            name='icon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mytest.Icon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marker',
            name='choice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mytest.Choice'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 7, 11, 7, 46, 360349, tzinfo=utc)),
        ),
    ]
