# Generated by Django 2.1 on 2018-09-07 11:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0009_auto_20180907_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 7, 11, 32, 24, 291345, tzinfo=utc)),
        ),
    ]
