# Generated by Django 2.1 on 2018-09-07 11:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0011_auto_20180907_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytest.Choice'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 7, 11, 43, 33, 327021, tzinfo=utc)),
        ),
    ]
