# Generated by Django 2.1 on 2018-09-10 09:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0014_auto_20180910_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 10, 9, 13, 49, 297890, tzinfo=utc)),
        ),
    ]
