# Generated by Django 2.1 on 2018-09-17 05:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0016_auto_20180910_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='choice',
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 17, 5, 51, 26, 269810, tzinfo=utc)),
        ),
    ]
